name: Docker Image CI

on:
  push:
    branches: [ develop ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t api:0.5.6
